### PR TITLE
Bump pomodoro timer version

### PR DESCRIPTION
**Pull request by FranzSkuffka**
I set the wrong defaults for the pomodoro timer - short break was 25 minutes 😨

### CODE REVIEW

**Comment by joshavanier** [comment]
Haha no worries. Thanks!

**Comment by FranzSkuffka** [comment]
Using this right now. Pretty awesome. We need to get a bell sound working so that the user gets reminded to come back to the workplace.

**Comment by FranzSkuffka** [comment]
There's something strange with the timer - can you please have a look and confirm it? For some reason the Log time and the timer time diverge 🙈

**Comment by joshavanier** [comment]
I'll look into it after breakfast haha

**Pull request merged**
